### ISSUE TITLE
thetvdb.com down causing TV Rename to crash

### ISSUE THREAD

**Issue by Andy-ABTec** [TV-Rename/tvrename#281]
One for the future maybe...
I'm getting 504 errors from thetvdb this morning, I guess they have a problem somewhere, but it seems to be causing this...
 
![image](https://user-images.githubusercontent.com/5175695/34826215-9e22a230-f6cd-11e7-84e7-6871f33f425a.png)

Nothing obvious in the log so I can't be sure they're related but does TV Rename check to see if thetvdb.com is up before it tries to use it?

**Comment by MarkSummerville** [comment]
Hmm

I added some error handling to the code recently to try and prevent this happening and degrade gracefully. Not so graceful it seems!

Unfortunately tvdb seems to have sorted itself out and I can’t reproduce. Also it looks like the logging can be improved to put more information about errors into the log. I have made a change for the next release for this. 

If it is still happening then put the updated nlog.config file in your tv rename directory and do a few background downloads to provoke the error and let me know what is in the log. That way we can fix that t

**Comment by MarkSummerville** [comment]
Does the log have any Error rows at all?

**Comment by Andy-ABTec** [comment]
A couple at the top of the log...
I've grabbed a copy of the whole log file just in case you want it...

````2018-01-11 13:26:09|INFO| TV Rename started with args: 
2018-01-11 13:26:09|INFO| Starting new instance
2018-01-11 13:26:09|INFO| Loading Cache from: C:\Users\Andy\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml
2018-01-11 13:26:09|INFO| Loading Settings from C:\Users\Andy\AppData\Roaming\TVRename\TVRename\2.1\TVRenameSettings.xml
2018-01-11 13:27:04|INFO| Status on screen updated: Connecting to TVDB
2018-01-11 13:27:05|INFO| Status on screen updated: 
2018-01-11 13:27:05|INFO| Status on screen updated: TheTVDB Languages
2018-01-11 13:27:05|INFO| Status on screen updated: 
2018-01-11 13:27:14|INFO| Status on screen updated: Code 24 Overview
2018-01-11 13:27:14|ERROR| Error obtaining https://api.thetvdb.com/series/24
2018-01-11 13:27:14|ERROR| System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.HTTPHelper.JsonHTTPGETRequest(String url, Dictionary`2 parameters, String authToken, String lang)
   at TVRename.TheTVDB.DownloadSeriesNow(Int32 code, Boolean episodesToo, Boolean bannersToo)
2018-01-11 13:27:14|INFO| Status on screen updated: 
2018-01-11 13:27:15|WARN| Issue with series 114171
2018-01-11 13:27:15|WARN| {
  "aliases": [
    "24 h Berlin  Ein Tag im Leben"
  ],
  "banner": "graphical/114171-g.jpg",
  "firstAired": "2009-09-05",
  "id": 114171,
  "network": "RBB",
  "overview": null,
  "seriesName": null,
  "status": "Ended"
}
2018-01-11 13:28:25|ERROR| Error obtaining https://api.thetvdb.com/search/series: The remote server returned an error: (404) Not Found.
2018-01-11 13:28:25|INFO| Status on screen updated:

**Comment by Andy-ABTec** [comment]
Seems fine, I've updated my Nlog.config from master as suggested...

I can probably break thetvdb access by fiddling with my network configuration and simulating a site down which might generate the relevant errors again, would you like me to try or leave it for now?

**Comment by MarkSummerville** [comment]
If you are able to that’d be good. 404 and no connection seem to be handled
gracefully for me

**Comment by Andy-ABTec** [comment]
Mmm, can't reproduce the error, Ive tried a number of tactics, but tv rename gracefully handles all of them!
I need to dig a bit deeper, I'm starting to wonder if it was a specific response from thetvdb that was causing the problem

**Comment by JoeBiellik** [comment]
I can't comment on the source for this crash, but over the last couple of days of working with TheTVDB API, I've received a couple of random 500 error responses that I couldn't reproduce. I think TVDB's servers occasionally have short blips - I imagine they are under high load.

**Comment by Andy-ABTec** [comment]
Might as well shut this for now then...
