### ISSUE TITLE
InvalidOperationException causes crash

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#313]
Saw this error in some logs from the boards:

```
2018-01-31 20:47:54|INFO| TV Rename started with args:  
2018-01-31 20:47:54|INFO| Starting new instance 
2018-01-31 20:47:54|ERROR| Application exiting with error System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at TVRename.App.ApplicationBase.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at TVRename.App.Program.Main(String[] args) 
```

Not sure whether that is enough to diagnose?

**Comment by JoeBiellik** [comment]
I've seen this or a very similar error on startup a couple of times, but I couldn't reproduce it consistently. I think its a race condition between the splashscreen UI starting and updating.

**Comment by cdbassett** [comment]
I am getting this exact error every time I try to start TVRename. I have a substantial existing DB of shows (...\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml is 10mb).

A quick google comes up with this:
https://stackoverflow.com/questions/808867/invoke-or-begininvoke-cannot-be-called-on-a-control-until-the-window-handle-has

Also having the issue that I can't use the old version either because it crashes when doing a scan.

**Comment by MarkSummerville** [comment]
@JoeBiellik Can you take a look at that change please and see if it resolves the issue for you? If so then we can release with 2.3.3

**Comment by JoeBiellik** [comment]
Changes look okay but I can't verify it does anything as I have only ever had this issue a couple of times while debugging, perhaps @cdbassett could try?

**Comment by cdbassett** [comment]
I don't have the project set up to build, but I could test with a binary.

**Comment by MarkSummerville** [comment]
OK - will release to beta ASAP

**Comment by MarkSummerville** [comment]
@cdbassett Please try https://github.com/TV-Rename/tvrename/releases/tag/2.3.3-rc1 and let us know how you get on

**Comment by cdbassett** [comment]
It starts up fine now, thanks so much!

**Comment by MarkSummerville** [comment]
2018-03-10 19:45:27|FATAL| UNHANDLED ERROR System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.

Server stack trace: 
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at TVRename.Ipc.RemoteClient.FocusWindow()
   at TVRename.App.Program.Main(String[] args)
