### ISSUE TITLE
SynchronizationLockException causes crash

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#314]
User 'Gene' reported this error on the Forums

```
System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
   at TVRename.TVDoc.GenerateEpisodeDict(ShowItem si)
   at TVRename.TVDoc.GenDict()
   at TVRename.TVDoc.DoDownloadsFG()
   at TVRename.TVDoc.ActionGo(List`1 shows)
   at TVRename.TVDoc.QuickScan(Boolean doMissingRecents, Boolean doFilesInDownloadDir)
   at TVRename.UI.QuickScan()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Seemed like there was an issue connecting to TVDB at the time, but nevertheless this should not have crashed the app.

**Comment by MarkSummerville** [comment]
Error log shows:

```
2018-02-04 16:11:44|ERROR| {
  "apikey": "5FEC454623154441"
} System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.HTTPHelper.JsonHTTPPOSTRequest(String url, JObject request)
   at TVRename.TheTVDB.Login() 
2018-02-04 16:11:44|INFO| Status on screen updated: ERROR CONNECTING TO TVDB 
2018-02-04 16:11:44|INFO| Status on screen updated:  
2018-02-04 16:11:44|INFO| Application exiting 
```
