### ISSUE TITLE
Introduce retry for Web Timeout issues

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#318]
Seen a few issues in the forums about timeouts - maybe we should introduce some timeout code?

```
System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.HTTPHelper.JsonHTTPPOSTRequest(String url, JObject request)
   at TVRename.TheTVDB.Login() 

```

**Comment by MarkSummerville** [comment]
another example

```
2018-01-31 20:29:30|WARN| Error obtaining https://api.thetvdb.com/updated/query: from lastupdated query -since(local) 28/01/2018 20:50:01 
2018-01-31 20:29:30|WARN| System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.TheTVDB.GetUpdates() System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.TheTVDB.GetUpdates() 
```

**Comment by MarkSummerville** [comment]
and another

```
2018-01-31 20:44:13|ERROR| Error obtaining https://api.thetvdb.com/series/292174 
2018-01-31 20:44:13|ERROR| System.Net.WebException: The remote server returned an error: (522) Origin Connection Time-out.
   at System.Net.HttpWebRequest.GetResponse()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.HTTPHelper.JsonHTTPGETRequest(String url, Dictionary`2 parameters, String authToken, String lang)
   at TVRename.TheTVDB.DownloadSeriesNow(Int32 code, Boolean episodesToo, Boolean bannersToo) System.Net.WebException: The remote server returned an error: (522) Origin Connection Time-out.
   at System.Net.HttpWebRequest.GetResponse()
   at TVRename.HTTPHelper.HTTPRequest(String method, String url, String json, String contentType, String authToken, String lang)
   at TVRename.HTTPHelper.JsonHTTPGETRequest(String url, Dictionary`2 parameters, String authToken, String lang)
   at TVRename.TheTVDB.DownloadSeriesNow(Int32 code, Boolean episodesToo, Boolean bannersToo) 
```

**Comment by MarkSummerville** [comment]
Looks like the default is already 100 seconds
https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.110).aspx

so not sure there is that much point retrying after that time
