### ISSUE TITLE
Ipc.RemoteClient.Bind Issue

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#343]
I am running TV Rename 2.3.3 RC 4 on Windows Server 2012 R2 and have tried several versions since the original which worked for many years without problems crashed now all the new ones work for a few times then crash
the latest crash gave this report:

Failed to create an IPC Port: Access is denied.

   at System.Runtime.Remoting.Channels.Ipc.IpcServerChannel.StartListening(Object data)
   at TVRename.Ipc.RemoteClient.Bind(UI form, TVDoc settings)
   at TVRename.App.ApplicationBase.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at TVRename.App.Program.Main(String[] args)

**Comment by MarkSummerville** [comment]
Possibly ` channelProperties.Add("exclusiveAddressUse", false); ` will fix this. Research from here:

https://social.msdn.microsoft.com/Forums/en-US/7b1bf959-d801-40ff-b92a-3a19a5d9f926/failed-to-create-an-ipc-port-access-is-denied?forum=netfxremoting

https://social.msdn.microsoft.com/Forums/en-US/d154e4a9-3e31-41a5-944c-db867ca77e9e/ipcchannel-explicit-cleanup?forum=netfxremoting

@JoeBiellik this is way out of my comfort zone - anything obvious?

**Comment by JoeBiellik** [comment]
Only thing I could think of is the first instance being started as a different user/permission set than the second. Your fix is worth a go if we have a way to reproduce the bug.

**Comment by JoeBiellik** [comment]
@MarkSummerville Where you able to confirm that fixes it?

**Comment by MarkSummerville** [comment]
Not formally. I am checking to see whether this breaks anything. My plan was then to package up a version and send it back to the original submitter and asking them to verify
