### ISSUE TITLE
Multiple "Move" operation hangs

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#362]
From https://groups.google.com/forum/#!topic/tvrename/2yPOJNdc8YM

Hi there,

I've been having this issue for some time now. Verison 2.4 RC3. Windows 10 Pro.

If there are multiple shows ready to be renamed, and also require moving from their respective download folders, TVRename just pops up the progress screen and hangs. Nothing at all happens. I can "Pause" and "Cancel" without fuss, but the move operation does not work for me.

If they are Rename Only, multiples work correctly. If I select only 1 Move operation it works correctly. Appears to be only multiple Move operations.

Logs indicate the following:

2018-03-19 12:51:23|INFO| Move completed: L:\Media\TV Shows\Blacklist, The\Season 05\The.Blacklist.S05E12.HDTV.x264-SVA[rarbg]\The.Blacklist.S05E12.HDTV.x264-SVA.mkv to L:\Media\TV Shows\The Blacklist\Season 05\The Blacklist - S05E12 - The Cook.mkv  
2018-03-19 12:51:23|INFO| Testing L:\Media\TV Shows\Blacklist, The\Season 05\The.Blacklist.S05E12.HDTV.x264-SVA[rarbg] to see whether it should be tidied up 
2018-03-19 12:51:23|INFO| Deleting L:\Media\TV Shows\Blacklist, The\Season 05\The.Blacklist.S05E12.HDTV.x264-SVA[rarbg] 
2018-03-19 12:51:23|FATAL| Unhandled Exception in Process Single Action Alphaleonis.Win32.Filesystem.DirectoryNotEmptyException: (145) The directory is not empty: [\\?\L:\Media\TV Shows\Blacklist, The\Season 05\The.Blacklist.S05E12.HDTV.x264-SVA[rarbg]]
   at Alphaleonis.Win32.Filesystem.Directory.DeleteDirectoryCore(FileSystemEntryInfo fileSystemEntryInfo, KernelTransaction transaction, String path, Boolean recursive, Boolean ignoreReadOnly, Boolean continueOnNotExist, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.DirectoryInfo.Delete()
   at TVRename.ActionFileOperation.DeleteOrRecycleFolder(DirectoryInfo di)
   at TVRename.ActionCopyMoveRename.Go(Boolean& pause, TVRenameStats stats)
   at TVRename.TVDoc.ProcessSingleAction(Object infoIn) 
2018-03-19 13:02:12|FATAL| Unhandled Exception in ActionProcessor System.Threading.ThreadAbortException: Thread was being aborted.
   at TVRename.TVDoc.ActionProcessor(Object queuesIn) 
2018-03-19 13:02:12|WARN| Failed to complete the following action: Move, doing TVRename.ActionCopyMoveRename. Error was  
2018-03-19 13:02:12|WARN| Failed to complete the following action: Move, doing TVRename.ActionCopyMoveRename. Error was  
2018-03-19 13:02:12|WARN| Failed to complete the following action: Move, doing TVRename.ActionCopyMoveRename. Error was  
2018-03-19 13:02:12|WARN| Failed to complete the following action: Move, doing TVRename.ActionCopyMoveRename. Error was  
2018-03-19 13:02:12|WARN| Failed to complete the following action: Move, doing TVRename.ActionCopyMoveRename. Error was  
2018-03-19 13:02:12|WARN| Failed to complete the following action: Move, doing TVRename.ActionCopyMoveRename. Error was  

^ This final line continues until I kill the operation.

Let me know if you need anything further about the environment.

Cheers,

Craig.

**Comment by MarkSummerville** [comment]
Need to add error handling to return done=true and handle error at https://github.com/TV-Rename/tvrename/blob/8d358fb3018714c536af5a1c953584fd76891867/TVRename%23/ItemsAndActions/ActionCopyMoveRename.cs#L125

Update to include (true) as pararmeter: https://github.com/TV-Rename/tvrename/blob/8d358fb3018714c536af5a1c953584fd76891867/TVRename%23/ItemsAndActions/ActionItem.cs#L135 

Clean up more thoroughly at https://github.com/TV-Rename/tvrename/blob/8d358fb3018714c536af5a1c953584fd76891867/TVRename%23/TVRename/TVDoc.cs#L1697
