### ISSUE TITLE
Error while downloading after clicking Recent

### ISSUE THREAD

**Issue by WeyldFalcon** [TV-Rename/tvrename#385]
# Expected Behaviour

Should scan for recent files

# Current Behaviour

hangs then gives error "Error while downloading"

# Failure Information

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Click Scan Tab
2. Click Recent
3. Wait for Download Progress "Processing Updates from TVDB"
4. get error
5. go confirm TVDB is still up
6. scratch head

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
* TVRename Version: 2.4.2 RC3
* Firmware Version:
* Operating System: Windows 10
* SDK version:
* Toolchain version:

## XML Files

Please include your XML files from your user directory here

**Comment by MarkSummerville** [comment]
Can you get there log information too please?

**Comment by WeyldFalcon** [comment]
all 6 times i have tried so far

here is the section of the log I assume you are looking for

2018-05-03 20:42:26|FATAL| UNHANDLED EXCEPTION IN DOWNLOAD THREAD System.AggregateException: One or more errors occurred. ---> System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at TVRename.TheTVDB.<>c__DisplayClass48_0.<GetUpdates>b__0(JObject jsonResponse)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at TVRename.TheTVDB.GetUpdates()
   at TVRename.TVDoc.Downloader()
---> (Inner Exception #0) System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value, IFormatProvider provider)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at TVRename.TheTVDB.<>c__DisplayClass48_0.<GetUpdates>b__0(JObject jsonResponse)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass31_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )<---
 
2018-05-03 20:43:29|INFO| ******************************* 
[2.1.7z.txt](https://github.com/TV-Rename/tvrename/files/1973073/2.1.7z.txt)

**Comment by WeyldFalcon** [comment]
hmm, just noticed in the log before the UNHANDLED EXCEPTION every time is this line
2018-05-03 20:46:42|INFO| Page 4 of Grey's Anatomy had 27 episodes listed

**Comment by WeyldFalcon** [comment]
Also Noticed at the top of my show list <194031 not downloaded>

**Comment by MarkSummerville** [comment]
194031 is Bob's Burgers. Maybe try removing that to see if it fixes it?

Should not mater which type of scan you do. TV rername always updates its cache before any scan.

**Comment by MarkSummerville** [comment]
Also error handling here:

https://github.com/TV-Rename/tvrename/blob/501156c17248bb96b26ca0b9302ee652a56f56de/TVRename%23/TheTVDB/TheTVDB.cs#L1323

**Comment by intriken** [comment]
Also receiving the same error:


> 2018-05-03 19:37:16|WARN|  
> 2018-05-03 19:55:49|INFO| Doing downloads in the foreground... 
> 2018-05-03 19:55:49|INFO| ******************************* 
> 2018-05-03 19:55:49|INFO| Starting Background Download... 
> 2018-05-03 19:55:49|INFO| Status on screen updated: Updates list 
> 2018-05-03 19:55:55|INFO| Obtianed 1683 responses from lastupdated query #1 - since (local) 4/30/2018 12:26:27 AM - to (local) 5/3/2018 5:35:18 PM 
> 2018-05-03 19:55:55|INFO| Status on screen updated: Processing Updates from TVDB 
> 2018-05-03 19:56:02|INFO| Page 1 of Modern Family had 100 episodes listed 
> 2018-05-03 19:56:06|INFO| Page 2 of Modern Family had 100 episodes listed 
> 2018-05-03 19:56:07|INFO| Page 3 of Modern Family had 12 episodes listed 
> 2018-05-03 19:56:07|FATAL| UNHANDLED EXCEPTION IN DOWNLOAD THREAD System.OverflowException: Value was either too large or too small for an Int32.
>    at System.Convert.ToInt32(Int64 value)
>    at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
>    at TVRename.TheTVDB.GetUpdates()
>    at TVRename.TVDoc.Downloader() 
> 2018-05-03 19:56:07|INFO| Saving Cache to: C:\Users\Vince\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml 
> 2018-05-03 19:56:08|WARN|

**Comment by bgantzler** [comment]
Same problem. Started about a day ago. Looking in log and removing last show seens to make progress. But have removed supergirl, ransom, westworld, legion, SEAL Team, allowed the program to proceed and prcess correctly. Course I am missing shows.

Adding the shows back and scanning recent one by one worked and the error is now longer present.

**Comment by MarkSummerville** [comment]
Just checked a few changes into master that *may* fix this issue. If anyone can checkout & build, I'd be interested to know whether they still see the issue

**Comment by StuartMeeks** [comment]
and another in Episode.cs on line 256
```c#
this.Srv_LastUpdated = (int)r["lastUpdated"];
```

Again, the cast should be long instead of int.

If you're wondering why I don't submit a PR, it's because I don't know how. One day I'll ask one of my devs to help me out and show me.

**Comment by StuartMeeks** [comment]
It looks like there are a few places where epoch time is being parsed into an int causing an overflow where the epoch value is > int.MaxValue.  Weirdly, it's happening on the lastUpdated property of an episode, and today's epoch is roughly 1525442821 which is < int.MaxValue.

So we may be getting some weird data from TheTVDB, or we're doing something weird on our side. Changing a few more data types to long will hide the message, but might not solve the issue.

**Comment by StuartMeeks** [comment]
Submitted PR #387

**Comment by MarkSummerville** [comment]
@GeorgeBell1982 I agree that we need to do some sanity checking of that date. Simply accepting a future dated update time causes problems down the line as we use that time as the last update time. When requesting updates, we ask for updates since the max update time.

I have raised the issue here https://forums.thetvdb.com/viewtopic.php?f=17&t=47698&sid=8ab4c6c4589531ae91f5fb6618c971dd to ask TVDB to address the root cause

**Comment by MarkSummerville** [comment]
TVDB are reporting that the issue is resolved

**Comment by WeyldFalcon** [comment]
RC5 resolved this issue!
This was the most amazing turnaround time I have ever seen on a software package!
