### ISSUE TITLE
Unhandled Exception in ScanWorker System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#422]
WHen I run a scan of just Star Trek (using Right Click -> Scan "Star Trek")
2018-06-10 19:51:53|INFO| Setting up 4 threads to download information from TVDB.com 
2018-06-10 19:51:53|INFO| Saving Cache to: C:\Users\ptrud\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml 
2018-06-10 19:51:53|INFO| Rename and missing check: Star Trek 
2018-06-10 19:51:53|FATAL| Unhandled Exception in ScanWorker System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TVRename.TVDoc.RenameAndMissingCheck(SetProgressDelegate prog, ICollection`1 showList)
   at TVRename.TVDoc.ScanWorker(Object o)

When I do the same for Star Trek: DS9, it works fine...

So the issue is with Star Trek.

**Comment by MarkSummerville** [comment]
https://groups.google.com/forum/#!msg/tvrename/J8sjC-TEGvo/EJegqWnSBAAJ

DVD order for star trek

**Comment by MarkSummerville** [comment]
Cant replicate
