### ISSUE TITLE
Force Refresh in Offline mode;; HTML view fails

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#446]
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at TVRename.ShowHtmlHelper.AppendShow(StringBuilder sb, ShowItem si)
   at TVRename.ShowHtmlHelper.GetShowHtmlOverviewNew(ShowItem si)
   at TVRename.UI.FillEpGuideHTML(ShowItem si, Int32 snum)
   at TVRename.UI.FillEpGuideHTML(TreeNode n)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MarkSummerville** [comment]
Looks like it's this row:
https://github.com/TV-Rename/tvrename/blob/57a5c41c147f0226a5cf05a51b36063560336042/TVRename/Utility/Helper/ShowHtmlHelper.cs#L67

**Comment by MarkSummerville** [comment]
Pretty sure this is fixed
