### ISSUE TITLE
Get missing actors working without errors in logs

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#470]
2018-08-11 08:28:50|ERROR| Unble to obtain actors for Revolting Rhymes System.Net.WebException: The remote server returned an error: (404) Not Found.

**Comment by MarkSummerville** [comment]
also this scenario

2018-08-11 15:58:48|INFO| Status on screen updated: Code 276396 (Everything) plus banners 
2018-08-11 15:58:48|INFO| Error obtaining page 2 of https://api.thetvdb.com/series/264108/episodes in lang en System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at TVRename.HttpHelper.HttpRequest(String method, String url, String json, String contentType, String authToken, String lang) in C:\Users\Mark\source\repos\TV-Rename\tvrename-master\TVRename\Utility\Helper\HTTPHelper.cs:line 39
   at TVRename.HttpHelper.JsonHttpGetRequest(String url, Dictionary`2 parameters, String authToken, String lang) in C:\Users\Mark\source\repos\TV-Rename\tvrename-master\TVRename\Utility\Helper\HTTPHelper.cs:line 59
   at TVRename.TheTVDB.GetEpisodes(Int32 id, String lang) in C:\Users\Mark\source\repos\TV-Rename\tvrename-master\TVRename\TheTVDB\TheTVDB.cs:line 858
