### ISSUE TITLE
Orphan BannerItem breaks cache loading

### ISSUE THREAD

**Issue by ashleywaite** [TV-Rename/tvrename#526]
This error and I think similar ones have happened to me several times forcing me to revert to older copies which is incredibly frustrating.

This simple error effectively broke my collection when it was trivial to recover from.

# Expected Behaviour
For TVRename to be able to load files that it saved itself!

Here are three behaviours I'd have expected:

**Validate before save**
When saving, actually check each item to be written out to ensure that you're not saving a file you will not actually load!

**Recover by discarding orphaned node**
When saving or loading, discard such an orphaned node, the worst case is that if it's ever needed again it'll need to be fetched.
If felt necessary, perhaps notify the user that it did that.

**Make error message more informative**
The error message only said that a key wasn't in a dictionary, and this made working out the problem really frustrating.
Had it simply mentioned the key that was missing, which in this case was Series ID 80595, I could have at least found the offending node in about 5 seconds and fixed it.
Instead I opened up the XML file and assuming that it was a broken `<BannersItem>` I selected each SeriesID listed within them and searched for any other occurrences in the file, until I found one that didn't have any, removed it, fixed.
Please help us fix our own things where possible by making errors helpful.

# Current Behaviour
On start up it fails to load with a key not found error, preventing me from loading my cache.
The error message is uninformative, and no actions are offered to attempt to repair the problem.

# Failure Information
Looking at the log file, the offending exception is this one:
```
    2018-12-28 16:17:06|WARN| Problem on Startup loading File System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
       at System.ThrowHelper.ThrowKeyNotFoundException()
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at TVRename.TheTVDB.ProcessXmlBannerCache(XElement r)
       at TVRename.TheTVDB.ProcessXml(XElement x)
       at TVRename.TheTVDB.LoadCache(FileInfo loadFrom)
```

Which based on the `ProcessXmlBannerCache()` function name, I figured it was an orphaned `<BannersItem>` node within the `<BannersCache>`.
The `<SeriesId>` within it referred to a series that had been deleted, and so no longer had a `<Series>` entry in the file, likely the reason it wasn't present in the dictionary being used here.
By editing `TheTVDB.xml` myself to remove that `<BannersItem>` node, it then successfully loaded.

## Steps to Reproduce
I've had this occur to me more than once, and I assume that it is connected to when I've earlier done:
1. Right click a TV show.
2. Selected `Edit Show`.
3. Selected a new show in the seach.
4. Saved change with `OK`

But it's certainly not consistent, and may have been some other action that is associated with a series being incorrectly detected.

I'm not sure exactly what actions within the program will result in this occurring, but it's fairly easy to create a data file that will fail in this exact manner in order to test a recovery solution.

1. Edit `TheTVDB.xml`
2. Add a `<BannersItem>` node that has an inappropriate Series ID with no matching `<Series>` node within the file. Such as the one that I encountered (which is a valid TVDB series ID, but wasn't in my file):
```
    <BannersItem>
      <SeriesId>80595</SeriesId>
      <Banners />
    </BannersItem>
```
3. Save file and load TVRename.

## Context
I'm using Windows 7 x64

## XML Files
I don't think any others are relevant, as I was able to manually correct the issue, but if they are then please let me know to provide.

## Log Files
```
2018-12-28 16:17:05|INFO| TV Rename 2.6.2 started with args:  
2018-12-28 16:17:05|INFO| Starting new instance 
2018-12-28 16:17:06|INFO| IE Version 11 is identified 
2018-12-28 16:17:06|INFO| Loading Cache from: C:\Users\Ashie\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml 
2018-12-28 16:17:06|TRACE| Lock Series for ProcessTVDBResponse 
2018-12-28 16:17:06|TRACE| Unlock series for (ProcessTVDBResponse) 
2018-12-28 16:17:06|WARN| Problem on Startup loading File System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at TVRename.TheTVDB.ProcessXmlBannerCache(XElement r)
   at TVRename.TheTVDB.ProcessXml(XElement x)
   at TVRename.TheTVDB.LoadCache(FileInfo loadFrom)
2018-12-28 16:17:06|INFO| Loading Settings from C:\Users\Ashie\AppData\Roaming\TVRename\TVRename\2.1\TVRenameSettings.xml 
2018-12-28 16:23:34|ERROR| Application exiting with error Microsoft.VisualBasic.ApplicationServices.NoStartupFormException: A startup form has not been specified.
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at TVRename.App.Program.Main(String[] args)
```

**Comment by MarkSummerville** [comment]
Thanks for the excellent write up. These problems have already been fixed in the latest beta release. 

Thank you for taking the time for writing up the details and sorry it caused you so many problems.
