### ISSUE TITLE
Scan fails if a show has been added with no root folder

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#532]
************** Exception Text **************
System.InvalidOperationException: DragDrop registration did not succeed. ---> System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
   at System.Windows.Forms.Control.SetAcceptDrops(Boolean accept)
   --- End of inner exception stack trace ---
   at System.Windows.Forms.Control.SetAcceptDrops(Boolean accept)
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Form.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmCreate(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MarkSummerville** [comment]
2019-01-02 15:10:43|INFO| Creating directory as it is missing:  
2019-01-02 15:10:43|INFO| Could not directory:  
2019-01-02 15:10:43|INFO| System.ArgumentException: Path is a zero-length string or contains only white space.
Parameter name: path
   at Alphaleonis.Win32.Filesystem.Path.GetLongPathCore(String path, GetFullPathOptions options)
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathCore(KernelTransaction transaction, String path, GetFullPathOptions options)
   at Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   at TVRename.CheckAllFoldersExist.CreateSeasonFolders(ShowItem si, Int32 snum, List`1 folders) System.ArgumentException: Path is a zero-length string or contains only white space.
Parameter name: path
   at Alphaleonis.Win32.Filesystem.Path.GetLongPathCore(String path, GetFullPathOptions options)
   at Alphaleonis.Win32.Filesystem.Path.GetFullPathCore(KernelTransaction transaction, String path, GetFullPathOptions options)
   at Alphaleonis.Win32.Filesystem.Directory.CreateDirectoryCore(KernelTransaction transaction, String path, String templatePath, ObjectSecurity directorySecurity, Boolean compress, PathFormat pathFormat)
   at TVRename.CheckAllFoldersExist.CreateSeasonFolders(ShowItem si, Int32 snum, List`1 folders)

**Comment by MarkSummerville** [comment]
https://groups.google.com/forum/#!topic/tvrename/KYwYTgHmEC0
