### ISSUE TITLE
Fatal Error- Full Scan - 2.6.4 Alpha 3

### ISSUE THREAD

**Issue by dss275** [TV-Rename/tvrename#538]
[TVRename.log](https://github.com/TV-Rename/tvrename/files/2737745/TVRename.log)

Receiving a fatal error when performing full scan.

Quick and Recent scans do not seem to have the issues

019-01-08 10:54:17|FATAL| Unhandled Exception in ScanWorker System.NullReferenceException: Object reference not set to an instance of an object.
   at TVRename.LibraryFolderFileFinder.Check(SetProgressDelegate prog, ICollection`1 showList, ScanSettings settings)
   at TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32 totPct, ICollection`1 showList, ScanSettings settings)
   at TVRename.FindMissingEpisodes.Check(SetProgressDelegate prog, ICollection`1 showList, ScanSettings settings)
   at TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32 totPct, ICollection`1 showList, ScanSettings settings)
   at TVRename.TVDoc.ScanWorker(Object o)

**Comment by MarkSummerville** [comment]
Thanks for providing the logs
Does the scan complete if you turn off the new feature 'Move Files within Library to Keep it Tidy'?
I think we'll need to add more logging to be able to find the issue

**Comment by MarkSummerville** [comment]
Hey try Alpha 4 to see whether that helps

**Comment by dss275** [comment]
I messed my test up.  I was trying to narrow down what was causing it by removing files in the search directory.  I thought I could restore them, but messed it up.  Now I am not getting the error and can not reproduce it.

I will see what I can do....

**Comment by MarkSummerville** [comment]
Hmm - looking at the error message then it looks like something in LibraryFolderFileFinder which doesn't look at the Search Folders. (so adjusting anything in the search folders should not matter, unless you search folders and library folders overlap.

**Comment by MarkSummerville** [comment]
I did do a minor change in alpha4 that may have helped.

**Comment by MarkSummerville** [comment]
Try alpha8 - another helpful change is in that one...
