### ISSUE TITLE
NRE in LibraryFolderFileFinder

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#540]
|FATAL| Unhandled Exception in ScanWorker System.NullReferenceException: Object reference not set to an instance of an object.     
at TVRename.LibraryFolderFileFinder.Check(SetProgressDelegate prog, ICollection`1 showList, ScanSettings settings)     
at TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32 totPct, ICollection`1 showList, ScanSettings settings)     
at TVRename.FindMissingEpisodes.Check(SetProgressDelegate prog, ICollection`1 showList, ScanSettings settings)     
at TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32 totPct, ICollection`1 showList, ScanSettings settings)     
at TVRename.TVDoc.ScanWorker(Object o)

**Comment by MarkSummerville** [comment]
Fix this at same time:


Unhandled Exception in ScanWorker   System.ArgumentNullException: Value cannot be null.  Parameter name: source     
at System.Linq.Enumerable.Where[TSource](IEnumerable`1   source, Func`2 predicate)     
at   TVRename.LibraryFolderFileFinder.Check(SetProgressDelegate prog,   ICollection`1 showList, ScanSettings settings)     
at   TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32   totPct, ICollection`1 showList, ScanSettings settings)     
at   TVRename.FindMissingEpisodes.Check(SetProgressDelegate prog, ICollection`1   showList, ScanSettings settings)     
at   TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32   totPct, ICollection`1 showList, ScanSettings settings)     at TVRename.TVDoc.ScanWorker(Object o)

**Comment by MarkSummerville** [comment]
Added fix for these 2
