### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#564]
2.6.6 |ERROR| Application exiting with error System.InvalidOperationException: Collection was modified; enumeration operation may not execute.     at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()     at System.Windows.Forms.Application.ExitInternal()     at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)     at System.Windows.Forms.Control.WndProcException(Exception e)     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)     at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)     at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)     at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)     at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)     at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()     at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()     at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)     at TVRename.App.Program.Main(String[] args)

**Comment by MarkSummerville** [comment]
| 2.6.6 |FATAL| Unhandled Exception in ScanWorker System.InvalidOperationException: Collection was modified; enumeration operation may not execute.     at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)     at System.Collections.Generic.List`1.Enumerator.MoveNextRare()     at TVRename.CleanDownloadDirectory.Go(ICollection`1 showList, ScanSettings settings)     at TVRename.CleanDownloadDirectory.Check(SetProgressDelegate prog, ICollection`1 showList, ScanSettings settings)     at TVRename.ScanActivity.Check(SetProgressDelegate prog, Int32 startpct, Int32 totPct, ICollection`1 showList, ScanSettings settings)     at TVRename.TVDoc.ScanWorker(Object o)
