### ISSUE TITLE
Win32Exception in SysOpen

### ISSUE THREAD

**Issue by MarkSummerville** [TV-Rename/tvrename#574]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the drive specified     at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)     at TVRename.Helpers.SysOpen(String what, String arguments) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the drive specified     at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)     at TVRename.Helpers.SysOpen(String what, String arguments)

System.ComponentModel.Win32Exception   (0x80004005): The specified executable is not a valid application for this OS   platform.     at   System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo   startInfo)     at   System.Diagnostics.Process.Start(ProcessStartInfo startInfo)     at TVRename.Helpers.SysOpen(String what,   String arguments) System.ComponentModel.Win32Exception (0x80004005): The   specified executable is not a valid application for this OS platform.     at   System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo   startInfo)     at   System.Diagnostics.Process.Start(ProcessStartInfo startInfo)     at TVRename.Helpers.SysOpen(String what,   String arguments)
--

**Comment by MarkSummerville** [comment]
ALready fixed
