### ISSUE TITLE
Fix Timeout for logging

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#663]
2020-01-14 16:31:49|FATAL| Application exiting with error NLog.NLogRuntimeException: Asynchronous exception has occurred. ---> System.TimeoutException: Timeout.
   --- End of inner exception stack trace ---
   at NLog.Common.AsyncHelpers.RunSynchronously(AsynchronousAction action)
   at NLog.LogFactory.Flush(TimeSpan timeout)
   at NLog.LogFactory.set_Configuration(LoggingConfiguration value)
   at TVRename.App.ApplicationBase.SetupLogging()
   at TVRename.App.ApplicationBase.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at TVRename.App.Program.Main(String[] args) NLog.ExceptionLoggedToInternalLogger: True

**Comment by snakefoot** [comment]
Never use ` throwExceptions="true"` in NLog.config it is intended for unit-testing only:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true" internalLogToConsole="true">
```
Instead use ` throwConfigExceptions="true"`:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwConfigExceptions="true" internalLogToConsole="true">
```

P.S. If interested in `internalLogToConsole="true"` should work, then remember to configure `internalLogLevel="Warn"`.

**Comment by SirSparkles** [comment]
@snakefoot Thanks for the advice
