### ISSUE TITLE
Retry on configuration save

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#675]
3.1 |ERROR| Failed to save Cache to C:\Users\\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml System.IO.IOException: The process cannot access the file 'C:\Users\\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml' because it is being used by another process.     
     at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
     at TVRename.TheTVDB.SaveCache()

**Comment by SirSparkles** [comment]
use this for a range of retries
http://www.thepollyproject.org/

**Comment by SirSparkles** [comment]
| 3.1.1 |ERROR| Failed to save Cache to C:\Users\u\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml System.IO.IOException: The process cannot access the file 'C:\Users\Michael\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml' because it is being used by another process.     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)     at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)     at TVRename.TheTvdbCachePersistor.SaveCache(ConcurrentDictionary`2 series, FileInfo cacheFile, Int64 timestamp)

**Comment by SirSparkles** [comment]
| 3.1.2 |ERROR| Failed to Save Configuration Files System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.     at TVRename.CachePersistor.SaveCache(ConcurrentDictionary`2 series, FileInfo cacheFile, Int64 timestamp)     at TVRename.TheTVDB.LocalCache.SaveCache()     at TVRename.UI.SaveCaches()     at TVRename.UI.saveToolStripMenuItem_Click(Object sender, EventArgs e)

**Comment by SirSparkles** [comment]
| 3.1.2 |ERROR| Failed to Save Configuration Files System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.     at TVRename.CachePersistor.SaveCache(ConcurrentDictionary`2 series, FileInfo cacheFile, Int64 timestamp)     at TVRename.TheTVDB.LocalCache.SaveCache()     at TVRename.UI.SaveCaches()     at TVRename.UI.saveToolStripMenuItem_Click(Object sender, EventArgs e)

**Comment by SirSparkles** [comment]
| 3.1.5 |ERROR| Failed to save Cache to C:\Users\\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml System.IO.FileNotFoundException: C:\Users\tpete\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml.7     at Alphaleonis.Win32.Filesystem.Directory.ExistsDriveOrFolderOrFile(KernelTransaction transaction, String path, Boolean isFolder, Int32 lastError, Boolean throwIfDriveNotExists, Boolean throwIfFolderOrFileNotExists)     at Alphaleonis.Win32.Filesystem.File.RestartCopyMoveOrThrowException(Int32 lastError, Boolean isFolder, Boolean isMove, KernelTransaction transaction, String sourcePathLp, String destinationPathLp, Nullable`1 moveOptions)     at Alphaleonis.Win32.Filesystem.File.CopyMoveCore(KernelTransaction transaction, Boolean driveChecked, Boolean isFolder, String sourcePath, String destinationPath, Nullable`1 copyOptions, Nullable`1 moveOptions, Boolean preserveDates, CopyMoveProgressRoutine progressHandler, Object userProgressData, CopyMoveResult copyMoveResult, PathFormat pathFormat)     at Alphaleonis.Win32.Filesystem.File.Move(String sourcePath, String destinationPath)     at TVRename.CachePersistor.RotateCacheFiles(FileInfo cacheFile)     at TVRename.CachePersistor.SaveCache(ConcurrentDictionary`2 series, FileInfo cacheFile, Int64 timestamp)

**Comment by SirSparkles** [comment]
| 3.2.9 |ERROR| Failed to save Cache to C:\Users\jtpau\AppData\Roaming\TVRename\TVRename\2.1\TheTVDB.xml System.IO.IOException: The requested operation cannot be performed on a file with a user-mapped section open.       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)     at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)     at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)     at TVRename.CachePersistor.SaveCache(ConcurrentDictionary`2 series, FileInfo cacheFile, Int64 timestamp)
