### ISSUE TITLE
UnauthorizedAccessException for ActionNfo.UpdateFile

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#684]
|FATAL| Unhandled Exception in Process Single Action System.UnauthorizedAccessException: Access to the path '...\tvshow.nfo' is denied.
     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
     at System.IO.FileStream.Init(String path, ..)
     at System.IO.FileStream..ctor(String path, ...)
     at System.IO.FileStream..ctor(String path, ...)
     at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
     at System.Xml.Linq.XDocument.Save(String fileName, SaveOptions options)
     at TVRename.ActionNfo.UpdateFile()

**Comment by SirSparkles** [comment]
ALready fixed
