### ISSUE TITLE
KeyNotfoundException

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#698]
Unhandled Exception in GetThread for Gogglebox id=268009 and lang=en System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.     at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)     at TVRename.TheTVDB.LocalCache.DownloadSeriesActors(Int32 code)     at TVRename.TheTVDB.LocalCache.DownloadSeriesNow(Int32 code, Boolean episodesToo, Boolean bannersToo, Boolean useCustomLangCode, String langCode)     at TVRename.TheTVDB.LocalCache.EnsureUpdated(SeriesSpecifier seriesd, Boolean bannersToo)     at TVRename.TheTVDB.CacheUpdater.GetThread(Object codeIn)

|FATAL| Unhandled Exception in GetThread for Doctor Who (2005) id=78804 and lang=en System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.     at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)     at TVRename.TheTVDB.LocalCache.EnsureUpdated(SeriesSpecifier seriesd, Boolean bannersToo)     at TVRename.TheTVDB.CacheUpdater.GetThread(Object codeIn)

|FATAL| Unhandled Exception in GetThread for Rick and Morty id=275274 and lang=en System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.     at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)     at TVRename.TheTVDB.LocalCache.DownloadSeriesActors(Int32 code)     at TVRename.TheTVDB.LocalCache.DownloadSeriesNow(Int32 code, Boolean episodesToo, Boolean bannersToo, Boolean useCustomLangCode, String langCode)     at TVRename.TheTVDB.LocalCache.EnsureUpdated(SeriesSpecifier seriesd, Boolean bannersToo)     at TVRename.TheTVDB.CacheUpdater.GetThread(Object codeIn)

**Comment by SirSparkles** [comment]
|FATAL| UNHANDLED EXCEPTION IN DOWNLOAD THREAD System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.     at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)     at TVRename.TheTVDB.LocalCache.ProcessEpisodes(Int32 id, Dictionary`2 episodesResponses)     at TVRename.TheTVDB.LocalCache.ProcessSeriesUpdate(JObject seriesResponse)     at TVRename.TheTVDB.LocalCache.ProcessUpdate(JObject jsonResponse)     at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()     at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)     at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
