### ISSUE TITLE
Crash when opening Preferences after upgrade to 4.4.0 (from 3.3.1)

### ISSUE THREAD

**Issue by staticanime** [TV-Rename/tvrename#811]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [X] I checked the [documentation](https://www.tvrename.com/manual/user/) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [X] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [X] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))
 - [X] It is not a general question( these should be asked on the [support forum](https://groups.google.com/forum/#!forum/tvrename))

# Bug Details

**Describe the bug**
Trying to click Preferences on 4.4.0 results in an app crash

**Expected Behaviour**
Preferences pane should open

**Current Behaviour**
Application closes

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Options'
2. Click on 'Preferences'
4. Application closes

**Error Log**
2021-10-29 22:00:11|INFO| Completed after activity: Cleaned up empty library folders 
2021-10-29 22:00:11|INFO| TV Rename free again (busy since 29/10/2021 22:00:10) 
2021-10-29 22:00:16|INFO| TV Rename is about to be busy doing Preferences are open since 29/10/2021 22:00:16 
2021-10-29 22:00:16|FATAL| UNHANDLED ERROR - Application.ThreadException System.InvalidOperationException: Unexpected value s.DefaultMovieProvider = libraryDefault
   at TVRename.Preferences.ChooseMovieRadioButton(ProviderType enumType)
   at TVRename.Preferences.PopulateFromEnums(TVSettings s)
   at TVRename.Preferences.Preferences_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by staticanime** [comment]
Seperate, but related, also get a crash trying to Add a Movie to the Movies section

`2021-10-29 22:05:21|INFO| Adding New Movie 
2021-10-29 22:05:21|INFO| TV Rename is about to be busy doing Add Movie since 29/10/2021 22:05:21 
2021-10-29 22:05:21|FATAL| UNHANDLED ERROR - Application.ThreadException System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at TVRename.MediaConfiguration.get_Code()
   at TVRename.MediaConfiguration.get_CachedData()
   at TVRename.MediaConfiguration.get_ShowName()
   at TVRename.CustomMovieName.NameFor(MovieConfiguration m, String styleString, Boolean urlEncode, Boolean isfilename)
   at TVRename.AddEditMovie..ctor(MovieConfiguration si, TVDoc doc)
   at TVRename.UI.AddMovie_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by staticanime** [comment]
Fixed both issues  by changing  <DefaultMovieProvider> in TVRenameSettings.xml to the below
<DefaultMovieProvider>2</DefaultMovieProvider>. It seems possible that this is not set correctly on upgrade from older versions?

**Comment by mkennedy2547** [comment]
> Fixed both issues by changing in TVRenameSettings.xml to the below 2. It seems possible that this is not set correctly on upgrade from older versions?

"to the below 2"  What do you mean?

**Comment by NitrousoxideN2O** [comment]
Sorry to reopen this, are you able to include a binary for the release of this bugfix?

**Comment by SirSparkles** [comment]
Should be fixed in 4.4.1. Will need to double check your settings. Any new ones introduced in 4.4 may not be set as you (or we) intended.

**Comment by SirSparkles** [comment]
Thanks for reporting.

Seems like there was a problem updating from 3.3.1 to 4.4 . TV Rename did not initalise any new settings correctly (upgrading from 3.3.1 to 4.4.1 will work OK though)

If you used 4.4 then you may want to check the following settings as they did not initialise:

SubsFolderNamesString = "subs;subtitle;vobsubs;sub;vobsub;subtitle";
DefMovieFolderFormat = singleDirectorySingleFile;
NFOMovies = true;
AutomateAutoAddWhenOneMovieFound = true;
AutomateAutoAddWhenOneShowFound = true;
CopySubsFolders = true; 
DeleteMovieFromDisk = false;
RemoveDownloadDirectoriesFilesMatchMovies = false;
RemoveDownloadDirectoriesFilesMatchMoviesLengthCheck = false;
RemoveDownloadDirectoriesFilesMatchMoviesLengthCheckLength = 8;
DefShowAlternateOrder = false;
DefMovieDoRenaming = true;
DefMovieDoMissingCheck = true;
DefMovieUseutomaticFolders = true;
DefMovieUseDefaultLocation = true;
DefMovieCheckFutureDatedMovies = false; 
DefMovieCheckNoDatedMovies = false; 
SuppressUpdateAvailablePopup = false;
DefaultMovieProvider = TVDoc.ProviderType.TMDB;
subtitleExtensions = ".srt;.sub;.sbv;.idx;.ifo;.smi;.ass;.ssa;.smi;.rt;.aqt;.jss;.cvd;.dks;.ttxt;.mpl;.pjs;.psb;.ssf;.svcd;.usf";
ExportMissingMoviesCSV = false;
ExportMissingMoviesXML = false;
ExportMoviesTXT = false;
ExportMoviesHTML = false;
ExportWTWTXT = false;
ReplaceMoviesWithBetterQuality = false;
IgnorePreviouslySeenMovies = false;
MovieFolderFormat = "{ShowName} ({Year})";
MovieFilenameFormat = "{ShowName} ({Year})";
FileNameCaseSensitiveMatch = false;
UpdateCheckInterval = TimeSpan.FromDays(1);

There are a lot of new settings!

**Comment by staticanime** [comment]
Thanks for that, I ended up backing up my settings and doing a clean install, didn't take very long to get set back up, and at least that ensured my settings were clean!
