### ISSUE TITLE
ObjectDisposedException + NullReferenceException

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#822]
| 4.4.3 |FATAL| UNHANDLED ERROR - GlobalExceptionHandler System.ObjectDisposedException: Cannot access a disposed object.  Object name: 'FolderMonitorProgress'.     at System.Windows.Forms.Control.CreateHandle()     at System.Windows.Forms.Form.CreateHandle()     at System.Windows.Forms.Control.get_Handle()     at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)     at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)     at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)     at TVRename.BulkAddShow.FmpShower()     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)     at System.Threading.ThreadHelper.ThreadStart()

**Comment by SirSparkles** [comment]
and

| 4.4.4 |FATAL| UNHANDLED ERROR - Application.ThreadException System.NullReferenceException: Object reference not set to an instance of an object.     at TVRename.UI.TabControl1_DrawItem(Object sender, DrawItemEventArgs e)     at System.Windows.Forms.TabControl.OnDrawItem(DrawItemEventArgs e)     at System.Windows.Forms.TabControl.WmReflectDrawItem(Message& m)     at System.Windows.Forms.TabControl.WndProc(Message& m)     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
