### ISSUE TITLE
Crash attempting to pull in TVDB data for a newly added show

### ISSUE THREAD

**Issue by staticanime** [TV-Rename/tvrename#843]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [x] I checked the [documentation](https://www.tvrename.com/manual/user/) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [x] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [x] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on the [Idea Wall](http://ideas.theideawall.com/TVRename/Forum/Details/8dea3275-4010-4bab-9763-a8bb613517e0))
 - [x] It is not a general question( these should be asked on the [support forum](https://groups.google.com/forum/#!forum/tvrename))

# Bug Details

**Describe the bug**
Added new show (Dogs in Space), and attempted a Refresh to pull in the show data. On doing so, TVRename crashed and closed

**Expected Behaviour**

Show information should be downloaded and Season/Episode info polulated

**Current Behaviour**

Crash to Desktop

**To Reproduce**
Steps to reproduce the behaviour:
1. Add show to Library (I did so via Bulk Add Shows)
2. Right Click show and Force Refresh (This didn't pull in any information)
3. Edit show and click Search
4. Crash

Error log below, and URL for the show on TVDB: https://thetvdb.com/series/dogs-in-space

```2021-11-23 15:11:36|INFO| TV Rename is about to be busy doing Edit TV Show since 23/11/2021 15:11:36 
2021-11-23 15:11:41|INFO| Status on screen updated: Dogs in Space Overview 
2021-11-23 15:11:42|WARN| Exception caught on attempt 1 of 3 to get https://api4.thetvdb.com/v4/seasons/1936837/extended - will retry after delay 00:00:02: The remote server returned an error: (404) Not Found. 
2021-11-23 15:11:42|WARN| Exception caught on attempt 1 of 3 to get https://api4.thetvdb.com/v4/seasons/1936838/extended - will retry after delay 00:00:02: The remote server returned an error: (404) Not Found. 
2021-11-23 15:11:44|WARN| Exception caught on attempt 2 of 3 to get https://api4.thetvdb.com/v4/seasons/1936837/extended - will retry after delay 00:00:02: The remote server returned an error: (404) Not Found. 
2021-11-23 15:11:44|WARN| Exception caught on attempt 2 of 3 to get https://api4.thetvdb.com/v4/seasons/1936838/extended - will retry after delay 00:00:02: The remote server returned an error: (404) Not Found. 
2021-11-23 15:11:46|WARN| Exception caught on attempt 3 of 3 to get https://api4.thetvdb.com/v4/seasons/1936838/extended - cancelling: The remote server returned an error: (404) Not Found. 
2021-11-23 15:11:46|WARN| Show with Id 405449 is no longer available from TVDB (got a 404). 
2021-11-23 15:11:46|WARN| Exception caught on attempt 3 of 3 to get https://api4.thetvdb.com/v4/seasons/1936837/extended - cancelling: The remote server returned an error: (404) Not Found. 
2021-11-23 15:11:46|WARN| Show with Id 405449 is no longer available from TVDB (got a 404). 
2021-11-23 15:11:47|FATAL| UNHANDLED ERROR - Application.ThreadException System.AggregateException: One or more errors occurred. ---> TVRename.MediaNotFoundException: Show with TVDB Id 405449 is no longer found on TVDB. Please Update
   at TVRename.TheTVDB.API.GetUrl(ISeriesSpecifier code, String uri, String requestedLanguageCode, MediaType type)
   at TVRename.TheTVDB.API.GetSeasonEpisodesV4(ISeriesSpecifier id, Int32 seasonId, String requestedLanguageCode)
   at TVRename.TheTVDB.LocalCache.<>c__DisplayClass99_0.<ReloadEpisodesV4>b__0(Season s)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) TVRename.MediaNotFoundException: Show with TVDB Id 405449 is no longer found on TVDB. Please Update
   at TVRename.TheTVDB.API.GetUrl(ISeriesSpecifier code, String uri, String requestedLanguageCode, MediaType type)
   at TVRename.TheTVDB.API.GetSeasonEpisodesV4(ISeriesSpecifier id, Int32 seasonId, String requestedLanguageCode)
   at TVRename.TheTVDB.LocalCache.<>c__DisplayClass99_0.<ReloadEpisodesV4>b__0(Season s)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

---> (Inner Exception #1) TVRename.MediaNotFoundException: Show with TVDB Id 405449 is no longer found on TVDB. Please Update
   at TVRename.TheTVDB.API.GetUrl(ISeriesSpecifier code, String uri, String requestedLanguageCode, MediaType type)
   at TVRename.TheTVDB.API.GetSeasonEpisodesV4(ISeriesSpecifier id, Int32 seasonId, String requestedLanguageCode)
   at TVRename.TheTVDB.LocalCache.<>c__DisplayClass99_0.<ReloadEpisodesV4>b__0(Season s)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---

```

**Comment by staticanime** [comment]
*NOTE* Switched back to the v3 TVDB API, and it works fine, so issue is v4 TVDB API specific, so this can probably be closed off

**Comment by SirSparkles** [comment]
The v4 API was having some issues yesterday, but look like they are sorted now.  TVR should not have crashed in any event, but  v4 should work again
