### ISSUE TITLE
ODE

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#861]
|FATAL| UNHANDLED ERROR - Application.ThreadException System.ObjectDisposedException: Cannot access a disposed object.  Object name: 'ObjectListViewFlickerFree'.     at System.Windows.Forms.Control.CreateHandle()     at System.Windows.Forms.ListView.CreateHandle()     at System.Windows.Forms.Control.get_Handle()     at System.Windows.Forms.Control.PointToClientInternal(Point p)     at BrightIdeasSoftware.SimpleDropSink.HandleTimerTick()     at System.Windows.Forms.Timer.OnTick(EventArgs e)     at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SirSparkles** [comment]
| 4.5.2 |FATAL| UNHANDLED ERROR - Application.ThreadException System.ObjectDisposedException: Cannot access a disposed object.  Object name: 'ObjectListViewFlickerFree'.     at System.Windows.Forms.Control.CreateHandle()     at System.Windows.Forms.ListView.CreateHandle()     at System.Windows.Forms.Control.get_Handle()     at System.Windows.Forms.Control.PointToClientInternal(Point p)     at BrightIdeasSoftware.SimpleDropSink.HandleTimerTick()     at System.Windows.Forms.Timer.OnTick(EventArgs e)     at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
