### ISSUE TITLE
4.5.4 Major Issues

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#890]
| 4.5.4 |FATAL| UNHANDLED ERROR - Application.ThreadException System.InvalidOperationException: ListView virtualization requires a valid ListViewItem to be provided by the RetrieveVirtualItem event or in the OnRetrieveVirtualItem method.     at System.Windows.Forms.ListView.WmReflectNotify(Message& m)     at System.Windows.Forms.ListView.WndProc(Message& m)     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

and

| 4.5.4 |FATAL| UNHANDLED ERROR - Application.ThreadException System.NullReferenceException: Object reference not set to an instance of an object.     at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)     at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)     at System.Windows.Forms.ListView.WndProc(Message& m)     at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)     at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

and

| 4.5.4 |FATAL| UNHANDLED ERROR - Application.ThreadException System.NullReferenceException: Object reference not set to an instance of an object.     at BrightIdeasSoftware.ModelObjectComparer.Compare(Object x, Object y)     at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)     at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)     at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)     at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)     at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)

and

| 4.5.4 |FATAL| UNHANDLED ERROR - Application.ThreadException System.NullReferenceException: Object reference not set to an instance of an object.     at BrightIdeasSoftware.ModelObjectComparer.Compare(Object x, Object y)     at System.Collections.Generic.ArraySortHelper`1.InsertionSort(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)     at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)     at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)

**Comment by SirSparkles** [comment]
Fixed in 4.5.6

**Comment by SirSparkles** [comment]
Also - removing the layout.xml seems to resolve the issue
