### ISSUE TITLE
libraryDefault

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#919]
| 4.7 |FATAL| UNHANDLED ERROR - Application: 
Unexpected value s.DefaultMovieProvider = libraryDefault
     at TVRename.Preferences.ChooseMovieRadioButton(ProviderType enumType)
     at TVRename.Preferences.PopulateFromEnums(TVSettings s)

**Comment by SirSparkles** [comment]
Will leave this unless it returns. Can only be because a config file has been changed
