### ISSUE TITLE
Use HttpRequestException

### ISSUE THREAD

**Issue by SirSparkles** [TV-Rename/tvrename#927]
4.7.2 |FATAL| Unhandled Exception in GetThread for tv: (Library Default) TVDB:295760 TMDB:62643 TVMaze:-1 (,,) [Legends of Tomorrow] System[.AggregateException](https://my.papertrailapp.com/groups/12610562/events?q=%22.AggregateException%22&focus=1478469755962413067&selected=1478469755962413067): One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).) (Response status code does not indicate success: 404 (Not Found).) (Response status code does not indicate success: 404 (Not Found).) (Response status code does not indicate success: 404 (Not Found).) (Response status code does not indicate success: 404 (Not Found).)   ---> System.Net.Http[.HttpRequestException](https://my.papertrailapp.com/groups/12610562/events?q=%22.HttpRequestException%22&focus=1478469755962413067&selected=1478469755962413067): Response status code does not indicate success: 404 (Not Found).     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()     at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)     at TVRename.HttpHelper.<>c__DisplayClass6_0.<<HttpRequest>b__0>d.MoveNext()     --- End of inner exception stack trace ---   ---> (Inner Exception #1) System.Net.Http[.HttpRequestException](https://my.papertrailapp.com/groups/12610562/events?q=%22.HttpRequestException%22&focus=1478469755962413067&selected=1478469755962413067): Response status code does not indicate success: 404 (Not Found).     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()     at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)     at TVRename.HttpHelper.<>c__DisplayClass6_0.<<HttpRequest>b__0>d.MoveNext()<---     ---> (Inner Exception #2) System.Net.Http[.HttpRequestException](https://my.papertrailapp.com/groups/12610562/events?q=%22.HttpRequestException%22&focus=1478469755962413067&selected=1478469755962413067): Response status code does not indicate success: 404 (Not Found).     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

**Comment by SirSparkles** [comment]
| 4.7.2 |FATAL| Unhandled Exception in GetThread for tv: (Library Default) TVDB:76808 TMDB:-1 TVMaze:-1 (,,) [Whose Line Is It Anyway? (US)] System.Net.Http[.HttpRequestException](https://my.papertrailapp.com/groups/12610562/events?q=%22.HttpRequestException%22&focus=1478661774953435205&selected=1478661774953435205): Response status code does not indicate success: 404 (Not Found).     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()     at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)     at TVRename.HttpHelper.<>c__DisplayClass6_0.<<HttpRequest>b__0>d.MoveNext()

**Comment by SirSparkles** [comment]
| 4.7.2 |FATAL| Failed to run Scan for Looked in qBitTorrent for the missing files to see if they are being downloaded System.Net.Http[.HttpRequestException](https://my.papertrailapp.com/groups/12610562/events?q=%22.HttpRequestException%22&focus=1478665084024410118&selected=1478665084024410118): No connection could be made because the target machine actively refused it. (192.168.1.120:8080)   ---> System.Net.Sockets[.SocketException](https://my.papertrailapp.com/groups/12610562/events?q=%22.SocketException%22&focus=1478665084024410118&selected=1478665084024410118) (10061): No connection could be made because the target machine actively refused it.     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs[.ThrowException](https://my.papertrailapp.com/groups/12610562/events?q=%22.ThrowException%22&focus=1478665084024410118&selected=1478665084024410118)(SocketError error, CancellationToken cancellationToken)     at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)     at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
