### ISSUE TITLE
New install 5.0.8 crashes on start

### ISSUE THREAD

**Issue by gordonfr** [TV-Rename/tvrename#990]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I am running the latest [version](https://github.com/TV-Rename/tvrename/releases)
- [ x] I checked the [documentation](https://www.tvrename.com/manual/user/) / [support forum](https://groups.google.com/forum/#!forum/tvrename) and found no answer
- [ x] I checked to make sure that this issue has not already been [filed](https://github.com/TV-Rename/tvrename/issues)
- [ x] It is a bug (i.e. something that is going wrong) and not a new feature (These should be raised on [Feature Upvote](https://tvrename.featureupvote.com/))
 - [ x] It is not a general question( these should be asked on the [support forum](https://groups.google.com/forum/#!forum/tvrename))

# Bug Details

**Describe the bug**
Installed TVRename and attempted to launch.

**Expected Behaviour**

Program would start

**Current Behaviour**

Program does not start.

**To Reproduce**
Happens everytime.  Tried restarting system and reinstalling TVRename

**Context**

* Operating System:
Windows 11

**Additional context**

## XML Files

No configuration files were created.

## Log Files

No logs available.

## Error messages

These system events are all I have to offer:

Log Name:      Application
Source:        .NET Runtime
Date:          8/16/2023 10:54:56 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      GordonLaptop
Description:
Application: TVRename.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at TVRename.App.Program.Main(String[] args)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-16T17:54:56.4615584Z" />
    <EventRecordID>24526</EventRecordID>
    <Correlation />
    <Execution ProcessID="3488" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>GordonLaptop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: TVRename.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at TVRename.App.Program.Main(String[] args)
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          8/16/2023 10:54:56 AM
Event ID:      1000
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          GORDONLAPTOP\free3
Computer:      GordonLaptop
Description:
Faulting application name: TVRename.exe, version: 5.0.8.0, time stamp: 0x6467e56c
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2134, time stamp: 0xc42b59fb
Exception code: 0xe0434352
Fault offset: 0x0000000000064c3c
Faulting process id: 0x0xDA0
Faulting application start time: 0x0x1D9D06AC45A6200
Faulting application path: C:\Program Files (x86)\TVRename\TVRename.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d8fa7c73-4233-4224-a2fe-9cd629794d3e
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-16T17:54:56.5842476Z" />
    <EventRecordID>24527</EventRecordID>
    <Correlation />
    <Execution ProcessID="21740" ThreadID="1200" />
    <Channel>Application</Channel>
    <Computer>GordonLaptop</Computer>
    <Security UserID="S-1-5-21-2529585993-1614614233-502066598-1001" />
  </System>
  <EventData>
    <Data Name="AppName">TVRename.exe</Data>
    <Data Name="AppVersion">5.0.8.0</Data>
    <Data Name="AppTimeStamp">6467e56c</Data>
    <Data Name="ModuleName">KERNELBASE.dll</Data>
    <Data Name="ModuleVersion">10.0.22621.2134</Data>
    <Data Name="ModuleTimeStamp">c42b59fb</Data>
    <Data Name="ExceptionCode">e0434352</Data>
    <Data Name="FaultingOffset">0000000000064c3c</Data>
    <Data Name="ProcessId">0xda0</Data>
    <Data Name="ProcessCreationTime">0x1d9d06ac45a6200</Data>
    <Data Name="AppPath">C:\Program Files (x86)\TVRename\TVRename.exe</Data>
    <Data Name="ModulePath">C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data Name="IntegratorReportId">d8fa7c73-4233-4224-a2fe-9cd629794d3e</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>
Log Name:      Application
Source:        Windows Error Reporting
Date:          8/16/2023 10:54:57 AM
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      
User:          GORDONLAPTOP\free3
Computer:      GordonLaptop
Description:
Fault bucket 2176640888164682173, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: TVRename.exe
P2: 5.0.8.0
P3: 6467e56c
P4: KERNELBASE.dll
P5: 10.0.22621.2134
P6: c42b59fb
P7: e0434352
P8: 0000000000064c3c
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4e24aeb6-0439-4c8f-bb88-06a3f8a64723.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.04a4355d-490e-4177-878a-7981cb6d32b9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6840228c-8383-4468-bf8c-c02f6e0b45a2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.efb53943-afe6-414c-a74d-0c34f314538e.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c71a4fb9-94d6-4701-91b8-1898da40a393.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TVRename.exe_8541fe47fc98992f5419939687615e6cdedc41d_cdf0ef3c_a2dd1988-2dbe-4eac-b2d2-5bd7e03bf0ef

Analysis symbol: 
Rechecking for solution: 0
Report Id: d8fa7c73-4233-4224-a2fe-9cd629794d3e
Report Status: 268435456
Hashed bucket: bb562fb92db0f9a7be34fb5afea589bd
Cab Guid: 0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-16T17:54:57.5011580Z" />
    <EventRecordID>24528</EventRecordID>
    <Correlation />
    <Execution ProcessID="21740" ThreadID="1200" />
    <Channel>Application</Channel>
    <Computer>GordonLaptop</Computer>
    <Security UserID="S-1-5-21-2529585993-1614614233-502066598-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">2176640888164682173</Data>
    <Data Name="BucketType">4</Data>
    <Data Name="EventName">APPCRASH</Data>
    <Data Name="Response">Not available</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">TVRename.exe</Data>
    <Data Name="P2">5.0.8.0</Data>
    <Data Name="P3">6467e56c</Data>
    <Data Name="P4">KERNELBASE.dll</Data>
    <Data Name="P5">10.0.22621.2134</Data>
    <Data Name="P6">c42b59fb</Data>
    <Data Name="P7">e0434352</Data>
    <Data Name="P8">0000000000064c3c</Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4e24aeb6-0439-4c8f-bb88-06a3f8a64723.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.04a4355d-490e-4177-878a-7981cb6d32b9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6840228c-8383-4468-bf8c-c02f6e0b45a2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.efb53943-afe6-414c-a74d-0c34f314538e.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c71a4fb9-94d6-4701-91b8-1898da40a393.tmp.xml</Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_TVRename.exe_8541fe47fc98992f5419939687615e6cdedc41d_cdf0ef3c_a2dd1988-2dbe-4eac-b2d2-5bd7e03bf0ef</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">d8fa7c73-4233-4224-a2fe-9cd629794d3e</Data>
    <Data Name="ReportStatus">268435456</Data>
    <Data Name="HashedBucket">bb562fb92db0f9a7be34fb5afea589bd</Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>

**Comment by SirSparkles** [comment]
Try https://groups.google.com/g/tvrename/c/Y1Na0H3hTf0 and then reinstalling TV Rename

Then if issues look in the logs for details: https://www.tvrename.com/manual/technical/#log-files

**Comment by SirSparkles** [comment]
@gordonfr Did that work?
